name: Lint

on: [push, pull_request]

jobs:
  markdownlint:
    name: 🧹 Markdown Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g markdownlint-cli@0.23.2
      - run: markdownlint '**/*.md' --ignore node_modules
  yamllint:
    name: 🧹 YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
